
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <nav className="bg-blue-500">
            <h1>happy</h1>
          </nav>
          <div>{children}</div>
        </div>

      </body>
    </html>
  );
}
