
// import "./globals.css";
import LogoutButton from "../_components/LogoutButton";
import ActiveLink from "../_components/ActiveLink";
import AuthGuard from "../_components/AuthGuard";
import Image from "next/image";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
      
        <AuthGuard>
          <div className="flex">

            {/* SIDEBAR */}
            <nav className=" border-r text-gray-900 h-screen w-64 fixed left-0 top-0 p-6">
              <Image src="/EstateHub_Logo2.png"
              width={200}
              height={10}
              alt="EstateHub_logo"></Image>
              <div className="h-[75%] flex flex-col justify-between mt-5 ">
                <div>
                  <ul className="grid gap-5">
                    <li><ActiveLink href="/dashboard" >Dashboard </ActiveLink></li>
                    <li><ActiveLink href="/properties" >Properties </ActiveLink></li>
                    <li><ActiveLink href="/dashboard/account" >My Account </ActiveLink></li>
                    <li><ActiveLink href="/dashboard/help" >Help & Support </ActiveLink></li>
                  </ul>
                </div>
                <div>
                  <LogoutButton/>
                </div>
              </div>
            </nav>

            {/* MAIN CONTENT */}
            <div className="ml-64 w-full">
              {/* TOP NAV */}
              <nav className="flex p-6 justify-between shadow">
                <div className="font-semibold">search</div>
                <div className="flex items-center gap-4">
                  <span>Notification</span>
                  <span>Agent Name</span>
                </div>
              </nav>

              {/* PAGE CONTENT */}
              <div className="p-6">
                {children}
              </div>
            </div>
          </div>

        </AuthGuard>
    
  );
}
